name: crc32
version: 0.1.6
description: A cyclic redundancy check calculator for Dart written in pure Dart.
author: Kai Sellgren <kaisellgren@gmail.com>
homepage: http://github.com/kaisellgren/CRC32
environment:
  sdk: '>=1.20.1 <3.0.0'
dev_dependencies:
  test: any
